site_name: EMA-BEERs
site_author: yahei-DTU
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Content: 
    - uv: uv.md
    - Cookiecutter: cookiecutter.md
    - Hydra: hydra.md
    - Unit Testing: unit_testing.md
    - W&B: wandb.md
    - CI and Dependabot: CI.md
    - Pre-commit: pre-commit.md
    - MkDocs: mkdocs.md
  - Extras:
    - Docker: docker.md
    - FastAPI: fastapi.md
